[deps]
Coool = "706ee060-34aa-11f0-27f9-7f12a106fbd6"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[sources]
Coool = {path = ".."}
Documenter = {path = "/Users/fons/Documents/Documenter.jl"}

[compat]
Documenter = "1"
julia = "1.11"
